-- MySQL Script generated by MySQL Workbench
-- 10/06/16 09:27:25
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Instituicao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Instituicao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Instituicao` (
  `Id_Instituicao` INT NOT NULL AUTO_INCREMENT,
  `InstituicaoDescricao` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Instituicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(128) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(128) NOT NULL,
  `DataNascimento` DATE NULL,
  `Id_Instituicao` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pessoa_Instituicao_idx` (`Id_Instituicao` ASC),
  CONSTRAINT `fk_Pessoa_Instituicao`
    FOREIGN KEY (`Id_Instituicao`)
    REFERENCES `mydb`.`Instituicao` (`Id_Instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Materia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Materia` (
  `idMateria` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idMateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Corpo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Corpo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Corpo` (
  `IdCorpo` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NULL,
  `Texto` VARCHAR(45) NULL,
  PRIMARY KEY (`IdCorpo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Questao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Questao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Questao` (
  `IdQuestao` INT NOT NULL AUTO_INCREMENT,
  `Ano` INT NOT NULL,
  `Titulo` VARCHAR(45) NULL,
  `Enunciado` VARCHAR(45) NULL,
  `IdMateria` INT NOT NULL,
  `IdCorpo` INT NOT NULL,
  PRIMARY KEY (`IdQuestao`),
  INDEX `fk_Questao_Materia1_idx` (`IdMateria` ASC),
  INDEX `fk_Questao_Corpo1_idx` (`IdCorpo` ASC),
  CONSTRAINT `fk_Questao_Materia1`
    FOREIGN KEY (`IdMateria`)
    REFERENCES `mydb`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questao_Corpo1`
    FOREIGN KEY (`IdCorpo`)
    REFERENCES `mydb`.`Corpo` (`IdCorpo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Opcao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Opcao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Opcao` (
  `idOpcao` INT NOT NULL AUTO_INCREMENT,
  `Texto` VARCHAR(45) NOT NULL,
  `Gabarito` INT NOT NULL,
  PRIMARY KEY (`idOpcao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`QuestaoOpcao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`QuestaoOpcao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`QuestaoOpcao` (
  `IdQuestao` INT NOT NULL,
  `IdOpcao` INT NOT NULL,
  PRIMARY KEY (`IdQuestao`, `IdOpcao`),
  INDEX `fk_Questao_has_Opcao_Opcao1_idx` (`IdOpcao` ASC),
  INDEX `fk_Questao_has_Opcao_Questao1_idx` (`IdQuestao` ASC),
  CONSTRAINT `fk_Questao_has_Opcao_Questao1`
    FOREIGN KEY (`IdQuestao`)
    REFERENCES `mydb`.`Questao` (`IdQuestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Questao_has_Opcao_Opcao1`
    FOREIGN KEY (`IdOpcao`)
    REFERENCES `mydb`.`Opcao` (`idOpcao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_has_Questao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pessoa_has_Questao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_has_Questao` (
  `IdPessoa` INT NOT NULL,
  `IdQuestao` INT NOT NULL,
  `AlternativaEscolhida` VARCHAR(45) NULL,
  PRIMARY KEY (`IdPessoa`, `IdQuestao`),
  INDEX `fk_Pessoa_has_Questao_Questao1_idx` (`IdQuestao` ASC),
  INDEX `fk_Pessoa_has_Questao_Pessoa1_idx` (`IdPessoa` ASC),
  CONSTRAINT `fk_Pessoa_has_Questao_Pessoa1`
    FOREIGN KEY (`IdPessoa`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pessoa_has_Questao_Questao1`
    FOREIGN KEY (`IdQuestao`)
    REFERENCES `mydb`.`Questao` (`IdQuestao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Videos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Videos` (
  `IdVideo` INT NOT NULL AUTO_INCREMENT,
  `URLVideo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdVideo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Livros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Livros` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Livros` (
  `IdLivro` INT NOT NULL AUTO_INCREMENT,
  `URLLivro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdLivro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Apostilas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Apostilas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Apostilas` (
  `idApostila` INT NOT NULL AUTO_INCREMENT,
  `URLApostila` VARCHAR(45) NULL,
  PRIMARY KEY (`idApostila`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InformacoesProva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`InformacoesProva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`InformacoesProva` (
  `IdInformacoesProva` INT NOT NULL,
  `DataProva` DATE NOT NULL,
  `DataInscricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdInformacoesProva`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
