language: java

jdk:
 - oraclejdk8 

addons:
 -postgresql: "9.3"
 -sonarqube: true

services: postgresql

script:
  - cd Pecomp
  - mvn clean install sonar:sonar 
  
notifications:
  slack: pecomp:ndjOMgO4ba39zJZBOW3nxICf
