language: java

addons:
 -postgresql: "9.3"
 -sonarqube: true

services: postgresql

jdk:
 - oraclejdk8 
 - oraclejdk7
 
script:
  - mvn clean install sonar:sonar 
  
notifications:
  slack: pecomp:ndjOMgO4ba39zJZBOW3nxICf
